/admin/callcenter/callcenter.go=admin.km.controller.Callcenter
/admin/callcenter/noticeWrite.go=notice.km.controller.NoticeWrite
/admin/callcenter/faqWrite.go=faq.km.controller.FaqWrite

/admin/product/productRegister.go=admin.product.km.controller.ProductRegister
/admin/product/productList.go=admin.product.km.controller.ProductList