#test

/admin/adminMain.go=admin.kth.controller.AdminMain

#Catalogue
/admin/catalogueRegister.go=admin.catalogue.jungyj.controller.CatalogueRegister
/admin/catalogue/pnameDuplicateCheck.go=admin.catalogue.jungyj.controller.PnameDuplicateCheck
/admin/catalogue/catalogueList.go=admin.catalogue.jungyj.controller.CatalogueList
/admin/catalogue/catalogueEdit.go=admin.catalogue.jungyj.controller.CatalogueEdit
/admin/catalogue/catalogueDelete.go=admin.catalogue.jungyj.controller.CatalogueDelete

#Category
/admin/category/categoryList.go=admin.category.jungyj.controller.CategoryList
/admin/category/categoryRegister.go=admin.category.jungyj.controller.CategoryRegister
/admin/category/categoryDelete.go=admin.category.jungyj.controller.CategoryDelete

#Supplier
/admin/supplier/supplierList.go=admin.supplier.jungyj.controller.SupplierList
/admin/supplier/supplierRegister.go=admin.supplier.jungyj.controller.SupplierRegister

#Purchase
/admin/purchase/purchaseRegister.go=admin.purchase.jungyj.controller.PurchaseRegister
/admin/purchase/purchaseEstimate.go=admin.purchase.jungyj.controller.PurchaseEstimate
/admin/purchase/purchaseList.go=admin.purchase.jungyj.controller.PurchaseList