#test

/admin/adminMain.go=admin.kth.controller.AdminMain

#catalogue
/admin/catalogueRegister.go=catalogue.jungyj.controller.CatalogueRegister
/admin/catalogue/pnameDuplicateCheck.go=catalogue.jungyj.controller.PnameDuplicateCheck
/admin/catalogue/catalogueList.go=catalogue.jungyj.controller.CatalogueList
/admin/catalogue/catalogueEdit.go=catalogue.jungyj.controller.CatalogueEdit
/admin/catalogue/catalogueDelete.go=catalogue.jungyj.controller.CatalogueDelete